extends "res://tests/audit_second_region_test.gd"
const UnifiedUI = preload("res://tests/unified_ui_test_driver.gd")
const L=preload("res://scripts/lightness_rules.gd")
func _run()->void:
	game=load("res://scenes/main.tscn").instantiate()
	if not game.has_method("_new_game"):game.free();quit(2);return
	root.add_child(game);await process_frame;game.state=AuditState.new();game._new_game()
	_geometry()
	await _playable_route()
	await _loaded_return()
	game._stop_audio();await create_timer(0.25).timeout;game.queue_free();await process_frame
	if failures==0:print("PASS: %d lightness geometry and scene checks" % checks)
	else:push_error("FAIL: %d of %d lightness checks" % [failures,checks])
	quit(0 if failures==0 else 1)
func _talk_light(id:String)->void:
	if game.active_modal:game._close_modal()
	game.world.teleport(game.world.interactables[id].pos);game._process(0)
	await _key(KEY_E)
	_check(game.active_modal,"Actual E opens "+id)
func _geometry()->void:
	var w=game.world
	_check(w._can_walk(L.SHORE) and w._can_walk(L.LANDING) and w._can_walk(L.RELIC_POSITION),"Authored departure/landing/lore are safe")
	_check(not w._can_walk(Vector2(1458,930)),"Water separates ordinary land from islet")
	_check(not w._can_step(L.SHORE,L.LANDING) and not w._can_step(L.LANDING,L.SHORE),"Long-step normal movement cannot tunnel either direction across water")
	_check(not w._can_step(Vector2(825,484),Vector2(1170,484)),"Segment test also prevents long-frame pond tunneling")
	_check(not w._can_step(Vector2(155,250),Vector2(460,250)),"Segment test also prevents long-frame building tunneling")
	_check(w._can_step(Vector2(500,420),Vector2(520,420)),"Normal unobstructed walking still works")
	_check(not w._can_step(Vector2(NAN,0),L.LANDING) and not w._can_step(L.SHORE,Vector2(INF,0)),"Invalid movement segment safely rejected")
	for facing in [Vector2.LEFT,Vector2.RIGHT,Vector2.UP,Vector2.DOWN]:
		for fraction in [0.0,0.5,0.9]:
			w.teleport(L.ISLET_CENTER+Vector2(36*fraction,0));w.facing=facing;w.companion_active=true
			_check(L.on_islet(w.companion_pos),"Teleport places companion inside islet")
			w._process(0.25)
			_check(L.on_islet(w.companion_pos),"Follower remains on islet under every cardinal facing")
	w.teleport(L.SHORE);w._update_nearby()
	_check(w.nearby_id=="reed_cross","Mainland cannot interact with nearby gated islet points across water")
	w.teleport(L.LANDING);w._update_nearby()
	_check(w.nearby_id!="reed_cross" and bool(w.interactables[w.nearby_id].get("islet",false)),"Islet does not offer an outward shore action")
func _playable_route()->void:
	game._new_game();await _talk_light("reed_cross")
	_check(_find_button(game.overlay,"踏苇过水")==null and _modal_text().contains("岑远"),"Locked crossing explains reachable free lesson")
	game._close_modal();game.state.quest_stage=6;game.state.ending="守望";game.state.choose_sect("问石门");game.state.gain_xp(180);game.state.recruit_companion();game._refresh()
	await _talk_light("mentor");_press("内功与轻身");_press("轻功 · 踏苇行")
	_check(_modal_text().contains("不收费") and _modal_text().contains("不改变普通行走碰撞"),"Lesson states cost and limited traversal")
	var stale=game.modal_actions[0];await _key(KEY_ESCAPE);stale.call()
	_check(not game.state.lightness_unlocked,"Cancelled/stale learning does not grant technique")
	await _talk_light("mentor");_press("内功与轻身");_press("轻功 · 踏苇行");_press("修习踏苇行")
	_check(game.state.lightness_unlocked and game.state.coins==24,"Real mentor teaches without spending coins")
	await _talk_light("reed_cross");_press("留在岸上")
	_check(not L.on_islet(game.world.player_pos),"Cancel leaves player safely on shore")
	await _talk_light("reed_cross");_press("踏苇过水")
	_check(L.on_islet(game.world.player_pos) and game.state.position==game.world.player_pos,"Explicit crossing synchronizes world and persistent position")
	_check(L.on_islet(game.world.companion_pos),"Companion lands safely with player")
	game._load()
	_check(L.on_islet(game.world.player_pos),"Immediate autosave/load preserves the island rather than old bank position")
	await _talk_light("reed_relic")
	_check(_modal_text().contains("只结算一次") and _find_button(game.overlay,"拓录残碑")!=null,"Discovery previews a bounded reward")
	var before_coins=game.state.coins
	_press("拓录残碑")
	_check(game.state.lightness_relics==[L.RELIC_ID] and game.state.coins==before_coins+18,"Actual pickup grants its unique reward")
	game._load();await _talk_light("reed_relic")
	_check(_find_button(game.overlay,"拓录残碑")==null and _modal_text().contains("已经收入江湖志"),"Reload/revisit cannot claim again")
	game._close_modal();game._show_journal()
	_check(_modal_text().contains("苇心残碑已拓录"),"Discovered lore is retained in journal")
	game._close_modal();await _talk_light("reed_return");_press("借石回岸")
	_check(game.world.player_pos==L.SHORE and game.state.position==L.SHORE,"Return updates both world and saved state")
	game._load();_check(game.world.player_pos==L.SHORE,"Return also survives immediate reload")
	game._show_map()
	var chart=_find_chart(game.overlay)
	_check(chart!=null and chart.markers.has("reed_relic") and chart.markers.has("reed_cross"),"Read-only map displays the new exploration points")
	game._close_modal();UnifiedUI.open_training(game);var battle_position:Vector2=game.world.player_pos;game.lightness_story.cross(true)
	_check(game.state.battle_active and game.world.player_pos==battle_position,"Direct traversal callback cannot escape a battle")
	UnifiedUI.leave(game)
func _loaded_return()->void:
	game._new_game();game.state.position=L.LANDING;game.world.teleport(L.LANDING)
	game._save();game._load()
	_check(not game.state.lightness_unlocked and L.on_islet(game.world.player_pos),"Recovery fixture may preserve safe island coordinate without lesson")
	await _talk_light("reed_relic")
	_check(_find_button(game.overlay,"拓录残碑")==null and _find_button(game.overlay,"借石回岸")!=null,"Recovery placement offers an exit, not an impossible reward button")
	_check(game.state.lightness_relics.is_empty(),"Recovery placement alone does not grant locked lore reward")
	game._close_modal();await _talk_light("reed_return");_press("借石回岸")
	_check(game.world.player_pos==L.SHORE and not game.state.lightness_unlocked,"Unlearned recovered traveller is never stranded")
