extends "res://tests/audit_second_region_test.gd"
const Slots=preload("res://scripts/local_save_slots.gd")
var directory:String
func _run()->void:
 directory="user://hero-slot-ui-"+str(Time.get_ticks_usec())
 DirAccess.make_dir_recursive_absolute(directory)
 game=load("res://scenes/main.tscn").instantiate();root.add_child(game)
 await process_frame
 game.state=AuditState.new();game.save_slots.store=Slots.new(directory);game._new_game()
 var store=game.save_slots.store
 await _key(KEY_F6)
 _check(_modal_text().contains("手记一") and game.modal_actions.size()==4,"F6 opens three manual slots and return")
 await _key(KEY_1)
 _check(store.describe(1).status=="valid" and game.status_label.text.contains("已写下"),"Empty first slot saves through real UI")
 var first=FileAccess.get_file_as_bytes(store.path_for(1))
 game.state.coins+=31
 game.save_slots.save_page();await _key(KEY_1)
 _check(_modal_text().contains("请确认") and _find_button(game.overlay,"确认重写")!=null,"Occupied slot requires explicit overwrite confirmation")
 var stale_save:Callable=game.modal_actions[0]
 await _key(KEY_2)
 stale_save.call()
 _check(FileAccess.get_file_as_bytes(store.path_for(1))==first,"Cancel overwrite preserves exact primary")
 await _key(KEY_1);await _key(KEY_ENTER)
 _check(FileAccess.get_file_as_bytes(store.path_for(1)+".bak")==first,"Confirmed overwrite preserves exact previous bytes")
 var primary=FileAccess.get_file_as_bytes(store.path_for(1));var backup=FileAccess.get_file_as_bytes(store.path_for(1)+".bak")
 game.save_slots.perform_save(1)
 _check(FileAccess.get_file_as_bytes(store.path_for(1))==primary and FileAccess.get_file_as_bytes(store.path_for(1)+".bak")==backup,"Duplicate save activation keeps meaningful backup")
 await _key(KEY_ESCAPE);await _key(KEY_F10)
 _check(game.modal_actions.size()==5,"F10 displays autosave plus three manual slots and return")
 await _key(KEY_2)
 _check(_find_button(game.overlay,"读取备份")!=null,"Slot detail offers validated previous backup")
 await _key(KEY_2)
 _check(_find_button(game.overlay,"确认读取")!=null and _modal_text().contains("替换当前内存"),"Backup load has clear replace-progress confirmation")
 var stale_load:Callable=game.modal_actions[0]
 await _key(KEY_2)
 stale_load.call()
 _check(game.state.coins==55,"Cancelling load preserves current in-memory branch")
 _press("读取备份");_press("确认读取")
 _check(game.state.coins==24 and game.current_screen=="explore","Backup resumes prior branch through common load transition")
 _check(FileAccess.get_file_as_bytes(store.path_for(1))==primary and FileAccess.get_file_as_bytes(store.path_for(1)+".bak")==backup,"Reading backup never rewrites manual files")
 # A second slot holds an independent later-region branch.
 game.state.quest_stage=6;game.state.ending="守望";game.state.choose_sect("问石门")
 game.state.side_stage=3;game.state.side_choice="rescue";game.state.side_reward_claimed=true;game.state.side_clues=2;game.state.side_found.assign(["boatman","ledger"])
 game.state.chapter_two_stage=4;game.state.chapter_two_ending="open_records";game.state.archive_clues.assign(["clerk","inscription"]);game.state.seal_sequence.assign([2,0,1])
 game.state.begin_mistwood();game.state.record_mist_gauge("rain")
 game._travel("mistwood",Vector2(410,425));await _key(KEY_F6);await _key(KEY_2)
 _check(store.describe(2).location=="mistwood","Second slot stores a separate fourth-region branch")
 _check(_modal_text().contains("雾竹坡"),"Slot preview translates region ID to Chinese")
 var second=FileAccess.get_file_as_bytes(store.path_for(2))
 game._show_title();_press("踏入江湖")
 _check(_modal_text().contains("手动手记不会删除"),"New journey explains autosave-only replacement")
 _press("确认新旅程")
 _check(game.state.quest_stage==0 and FileAccess.get_file_as_bytes(store.path_for(1))==primary and FileAccess.get_file_as_bytes(store.path_for(2))==second,"New game preserves both independent manual branches")
 game._show_title()
 _check(_find_button(game.overlay,"查阅手记")!=null,"Title discovers manual saves independently")
 _press("查阅手记");await _key(KEY_3);_press("读取当前版本");_press("确认读取")
 _check(game.world.map_id=="mistwood" and game.state.mist_gauges.has("rain"),"Title load restores actual map and branch progress")
 _check(game.world._can_walk(game.world.player_pos),"Manual slot restore passes safe-position recovery")
 # Corrupt current slot: only its known-good backup may be loaded.
 var corrupt=FileAccess.open(store.path_for(1),FileAccess.WRITE);corrupt.store_string("{bad");corrupt.close()
 game.save_slots.load_page();await _key(KEY_2)
 _check(_find_button(game.overlay,"读取当前版本")==null and _find_button(game.overlay,"读取备份")!=null,"Corrupt primary is not offered as a valid load; backup remains available")
 var before=game.state.to_dict();game.save_slots.perform_load(1,false)
 _check(game.state.to_dict()==before and game.status_label.text.contains("未改变"),"Failed load leaves current branch untouched")
 game.save_slots.detail(1);_press("读取备份");_press("确认读取")
 _check(game.state.coins==24,"Good backup remains recoverable after primary corruption")
 # Deterministic backup failure must be visible and not overwrite slot2.
 var blocked=store.path_for(2)+".bak.tmp"
 DirAccess.make_dir_recursive_absolute(blocked)
 game.state.coins=77;game.save_slots.save_page();await _key(KEY_2);_press("确认重写")
 _check(FileAccess.get_file_as_bytes(store.path_for(2))==second and game.status_label.text.contains("未能保存"),"Backup failure is visible and preserves previous slot")
 game._close_modal();game._start_battle("spar")
 await _key(KEY_F6);await _key(KEY_F10)
 _check(not game.active_modal and game.current_screen=="battle","Manual save and load shortcuts are blocked in combat")
 game.save_slots.save_page();game.save_slots.load_page()
 _check(not game.active_modal,"Direct menu calls also block combat")
 game._battle_action("flee");game._close_modal()
 game._stop_audio();await create_timer(0.25).timeout;game.queue_free();await process_frame
 if failures==0:print("PASS: %d manual save-slot UI checks" % checks)
 else:push_error("FAIL: %d of %d manual save-slot UI checks" % [failures,checks])
 quit(0 if failures==0 else 1)
